
project_id = "mqppvcrlvsgrsqelglod"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]

[functions.telnyx-phone-manager]
verify_jwt = true

[functions.check-telnyx-account]
verify_jwt = true

[functions.sync-telnyx-numbers]
verify_jwt = true

[functions.manage-phone-numbers]
verify_jwt = true

[functions.update-webhook-url]
verify_jwt = true
