
project_id = "mqppvcrlvsgrsqelglod"

[functions.send-estimate]
verify_jwt = true

[functions.send-invoice]
verify_jwt = true

[functions.telnyx-sms]
verify_jwt = true

[functions.execute-automation]
verify_jwt = true
