@echo off
echo Killing node processes...
taskkill /F /IM node.exe 2>nul
echo Waiting 2 seconds...
timeout /t 2 /nobreak >nul
echo Starting dev server...
cd "C:\Users\petru\Downloads\TEST FIX SITE\3\Fixlify-Main-main"
npm run dev
