
import React, { useState, useEffect, useCallback } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Send, Mail, MessageSquare, ArrowLeft, AlertCircle, Info, Link2, Copy, Check } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { useDocumentSending } from "@/hooks/useDocumentSending";
import { useCompanySettings } from "@/hooks/useCompanySettings";
import { needsCountryCode, suggestCountryCode } from "@/utils/phoneUtils";
import { toast } from "sonner";

interface UniversalSendDialogProps {
  isOpen: boolean;
  onClose: () => void;
  documentType: "estimate" | "invoice";
  documentId: string;
  documentNumber: string;
  total: number;
  contactInfo?: {
    name: string;
    email: string;
    phone: string;
  };
  onSuccess?: () => void;
}

// Local storage key for saving custom message templates
const STORAGE_KEY_PREFIX = 'fixlify_send_template_';

export const UniversalSendDialog = ({
  isOpen,
  onClose,
  documentType,
  documentId,
  documentNumber,
  total,
  contactInfo,
  onSuccess
}: UniversalSendDialogProps) => {
  const [sendMethod, setSendMethod] = useState<"email" | "sms">("email");
  const [sendTo, setSendTo] = useState("");
  const [customNote, setCustomNote] = useState("");
  const [validationError, setValidationError] = useState("");
  const [portalLink, setPortalLink] = useState<string | null>(null);
  const [linkCopied, setLinkCopied] = useState(false);
  const [hasLoadedSavedTemplate, setHasLoadedSavedTemplate] = useState(false);

  const { sendDocument, isProcessing } = useDocumentSending();
  const { companySettings } = useCompanySettings();

  // Storage key for this document type and send method
  const getStorageKey = useCallback((method: "email" | "sms") => {
    return `${STORAGE_KEY_PREFIX}${documentType}_${method}`;
  }, [documentType]);

  // Generate default message template
  // Note: Portal link is automatically generated and included by the backend
  // The message shown here is for preview only - actual portal link will be added by the server
  const generateDefaultMessage = (method: "email" | "sms") => {
    const clientName = contactInfo?.name || "Valued Customer";
    const docType = documentType === "estimate" ? "Estimate" : "Invoice";
    const companyName = companySettings?.company_name || "Your Company";

    if (method === "email") {
      // Note: Portal link is automatically included in the email by the server
      return `Hello ${clientName},

Please find your ${docType} #${documentNumber} attached. The total amount is $${total.toFixed(2)}.

A secure link to view and ${documentType === "estimate" ? "approve" : "pay"} online will be included automatically.

If you have any questions, please don't hesitate to contact us.

Best regards,
${companyName} Team`;
    } else {
      // Keep SMS short - backend will append the real portal URL
      return `Your ${docType} #${documentNumber} ($${total.toFixed(2)}) is ready.`;
    }
  };

  // Generate portal link preview (this is what will be sent)
  const generatePortalLink = useCallback(() => {
    // The actual portal link is generated by the backend with a secure token
    // This is just a placeholder to show the user what format it will take
    const baseUrl = window.location.origin;
    return `${baseUrl}/portal/${documentType}/[secure-token]`;
  }, [documentType]);

  // Set default values when dialog opens
  useEffect(() => {
    if (isOpen) {
      if (contactInfo) {
        if (sendMethod === "email" && contactInfo.email) {
          setSendTo(contactInfo.email);
        } else if (sendMethod === "sms" && contactInfo.phone) {
          setSendTo(contactInfo.phone);
        } else {
          setSendTo("");
        }
      }
      setValidationError("");
      setPortalLink(generatePortalLink());
      setLinkCopied(false);

      // Try to load saved template from localStorage
      const storageKey = getStorageKey(sendMethod);
      const savedTemplate = localStorage.getItem(storageKey);

      if (savedTemplate && !hasLoadedSavedTemplate) {
        // Replace placeholders in saved template with current values
        const clientName = contactInfo?.name || "Valued Customer";
        const docType = documentType === "estimate" ? "Estimate" : "Invoice";
        const companyName = companySettings?.company_name || "Your Company";

        let processedTemplate = savedTemplate
          .replace(/\[CLIENT_NAME\]/g, clientName)
          .replace(/\[DOC_TYPE\]/g, docType)
          .replace(/\[DOC_NUMBER\]/g, documentNumber)
          .replace(/\[TOTAL\]/g, total.toFixed(2))
          .replace(/\[COMPANY_NAME\]/g, companyName);

        setCustomNote(processedTemplate);
        setHasLoadedSavedTemplate(true);
      } else if (!hasLoadedSavedTemplate) {
        // Use default template
        setCustomNote(generateDefaultMessage(sendMethod));
        setHasLoadedSavedTemplate(true);
      }
    }
  }, [isOpen, sendMethod, contactInfo, documentType, documentId, documentNumber, total, companySettings, getStorageKey, generatePortalLink, hasLoadedSavedTemplate]);

  // Auto-save custom message to localStorage when it changes
  useEffect(() => {
    if (isOpen && customNote && hasLoadedSavedTemplate) {
      // Save a template version with placeholders for reuse
      const clientName = contactInfo?.name || "Valued Customer";
      const docType = documentType === "estimate" ? "Estimate" : "Invoice";
      const companyName = companySettings?.company_name || "Your Company";

      // Convert current values back to placeholders for template storage
      let templateToSave = customNote
        .replace(new RegExp(clientName, 'g'), '[CLIENT_NAME]')
        .replace(new RegExp(docType, 'g'), '[DOC_TYPE]')
        .replace(new RegExp(`#${documentNumber}`, 'g'), '#[DOC_NUMBER]')
        .replace(new RegExp(`\\$${total.toFixed(2)}`, 'g'), '$[TOTAL]')
        .replace(new RegExp(companyName, 'g'), '[COMPANY_NAME]');

      const storageKey = getStorageKey(sendMethod);
      localStorage.setItem(storageKey, templateToSave);
    }
  }, [customNote, isOpen, hasLoadedSavedTemplate, contactInfo, documentType, documentNumber, total, companySettings, sendMethod, getStorageKey]);

  // Update message template when send method changes
  useEffect(() => {
    if (isOpen && customNote === generateDefaultMessage(sendMethod === "email" ? "sms" : "email")) {
      setCustomNote(generateDefaultMessage(sendMethod));
    }
  }, [sendMethod]);

  // Reset form when dialog closes
  useEffect(() => {
    if (!isOpen) {
      setSendTo("");
      setCustomNote("");
      setValidationError("");
      setSendMethod("email");
      setPortalLink(null);
      setLinkCopied(false);
      setHasLoadedSavedTemplate(false);
    }
  }, [isOpen]);

  // Copy portal link to clipboard
  const handleCopyLink = useCallback(async () => {
    if (portalLink) {
      try {
        await navigator.clipboard.writeText(portalLink);
        setLinkCopied(true);
        toast.success("Link copied to clipboard!");
        setTimeout(() => setLinkCopied(false), 2000);
      } catch {
        toast.error("Failed to copy link");
      }
    }
  }, [portalLink]);

  // Validation functions
  const isValidEmail = (email: string): boolean => {
    if (!email) return false;
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
  };

  const isValidPhoneNumber = (phone: string): boolean => {
    if (!phone) return false;
    const cleaned = phone.replace(/\D/g, '');
    // Allow 10-15 digits for international numbers
    return cleaned.length >= 10 && cleaned.length <= 15;
  };

  const validateInput = (): boolean => {
    if (!sendTo.trim()) {
      setValidationError(`Please enter a ${sendMethod === "email" ? "email address" : "phone number"}`);
      return false;
    }

    if (sendMethod === "email" && !isValidEmail(sendTo)) {
      setValidationError("Please enter a valid email address (e.g., client@example.com)");
      return false;
    }

    if (sendMethod === "sms" && !isValidPhoneNumber(sendTo)) {
      setValidationError("Please enter a valid phone number");
      return false;
    }

    setValidationError("");
    return true;
  };

  const handleSend = async () => {
    if (!validateInput()) return;

    const result = await sendDocument({
      documentType,
      documentId,
      sendMethod,
      sendTo,
      customMessage: customNote || undefined,
      contactInfo
    });

    if (result.success) {
      onClose();
      if (onSuccess) {
        onSuccess();
      }
    }
  };

  const hasValidEmail = contactInfo?.email && isValidEmail(contactInfo.email);
  const hasValidPhone = contactInfo?.phone && isValidPhoneNumber(contactInfo.phone);

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-md w-[95vw] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-lg">
            <Send className="h-5 w-5 text-blue-600 flex-shrink-0" />
            <span className="truncate">Send {documentType === "estimate" ? "Estimate" : "Invoice"} #{documentNumber}</span>
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-6">
          {/* Document Summary */}
          <div className="bg-blue-50 p-3 rounded-lg">
            <p className="text-sm text-blue-800">
              <strong>Total:</strong> ${total.toFixed(2)}
            </p>
            {contactInfo?.name && (
              <p className="text-sm text-blue-800 truncate">
                <strong>Customer:</strong> {contactInfo.name}
              </p>
            )}
          </div>

          {/* Service Status Alert */}
          {(!hasValidEmail && !hasValidPhone) && (
            <Alert>
              <AlertCircle className="h-4 w-4" />
              <AlertDescription>
                No valid contact information found for this client. Please enter the recipient details manually.
              </AlertDescription>
            </Alert>
          )}

          {/* Send Method Selection */}
          <div className="space-y-3">
            <Label className="text-sm font-medium">Choose sending method:</Label>
            <RadioGroup value={sendMethod} onValueChange={(value: "email" | "sms") => setSendMethod(value)}>
              <div className={`flex items-center space-x-2 p-3 rounded-lg border ${
                sendMethod === "email" ? "border-blue-200 bg-blue-50" : "border-gray-200"
              } ${!hasValidEmail ? "opacity-50" : ""}`}>
                <RadioGroupItem value="email" id="email" disabled={!hasValidEmail && !sendTo} />
                <Mail className="h-4 w-4" />
                <Label htmlFor="email" className="flex-1 cursor-pointer">
                  Email
                  {!hasValidEmail && <span className="text-amber-600 text-xs ml-2">(No valid email on file)</span>}
                </Label>
              </div>
              
              <div className={`flex items-center space-x-2 p-3 rounded-lg border ${
                sendMethod === "sms" ? "border-blue-200 bg-blue-50" : "border-gray-200"
              } ${!hasValidPhone ? "opacity-50" : ""}`}>
                <RadioGroupItem value="sms" id="sms" disabled={!hasValidPhone && !sendTo} />
                <MessageSquare className="h-4 w-4" />
                <Label htmlFor="sms" className="flex-1 cursor-pointer">
                  SMS (Text Message)
                  {!hasValidPhone && <span className="text-amber-600 text-xs ml-2">(No valid phone on file)</span>}
                </Label>
              </div>
            </RadioGroup>
          </div>

          {/* Recipient Input */}
          <div className="space-y-2">
            <Label htmlFor="sendTo">
              {sendMethod === "email" ? "Email Address" : "Phone Number"}
            </Label>
            <Input
              id="sendTo"
              type={sendMethod === "email" ? "email" : "tel"}
              placeholder={sendMethod === "email" ? "client@example.com" : "Phone number"}
              value={sendTo}
              onChange={(e) => {
                const value = e.target.value;
                setSendTo(value);
                // Inline validation as user types
                if (value.trim()) {
                  if (sendMethod === "email" && !isValidEmail(value)) {
                    setValidationError("Please enter a valid email address (e.g., client@example.com)");
                  } else if (sendMethod === "sms" && !isValidPhoneNumber(value)) {
                    const digits = value.replace(/\D/g, '').length;
                    if (digits < 10) {
                      setValidationError(`Phone number too short (${digits} digits). Enter at least 10 digits.`);
                    } else if (digits > 15) {
                      setValidationError(`Phone number too long (${digits} digits). Maximum 15 digits allowed.`);
                    } else {
                      setValidationError("Please enter a valid phone number");
                    }
                  } else {
                    setValidationError("");
                  }
                } else {
                  setValidationError("");
                }
              }}
              className={validationError ? "border-red-500 focus:ring-red-500" : ""}
            />
            {validationError && (
              <p className="text-sm text-red-600">{validationError}</p>
            )}
            {sendMethod === "sms" && (
              <>
                {sendTo && needsCountryCode(sendTo) && (
                  <p className="text-xs text-amber-600">
                    {suggestCountryCode(sendTo)}
                  </p>
                )}
                <p className="text-xs text-muted-foreground">
                  Phone number will be automatically formatted. Include country code for best results (e.g., +1 for US/Canada).
                </p>
              </>
            )}
          </div>

          {/* Custom Message */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label htmlFor="customNote">Your Message</Label>
              {sendMethod === "sms" && (
                <span className={`text-xs font-medium ${
                  customNote.length > 160
                    ? "text-red-600"
                    : customNote.length > 140
                      ? "text-amber-600"
                      : "text-muted-foreground"
                }`}>
                  {customNote.length}/160 characters
                </span>
              )}
            </div>
            <Textarea
              id="customNote"
              placeholder="Add a personal message..."
              value={customNote}
              onChange={(e) => setCustomNote(e.target.value)}
              rows={sendMethod === "email" ? 6 : 3}
              className={`min-h-[80px] ${
                sendMethod === "sms" && customNote.length > 160
                  ? "border-red-500 focus:ring-red-500"
                  : ""
              }`}
            />
            {sendMethod === "sms" && customNote.length > 160 ? (
              <p className="text-xs text-red-600">
                Message exceeds 160 characters. It may be sent as multiple messages.
              </p>
            ) : sendMethod === "sms" && customNote.length > 140 ? (
              <p className="text-xs text-amber-600">
                Approaching SMS limit (160 chars). Consider shortening.
              </p>
            ) : (
              <p className="text-xs text-muted-foreground">
                Edit your message above. Your changes will be saved for next time.
              </p>
            )}
          </div>

          {/* Portal Link Preview (Read-only) */}
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <Link2 className="h-4 w-4 text-blue-600" />
              <Label className="text-sm font-medium">Secure Portal Link</Label>
              <span className="text-xs bg-blue-100 text-blue-700 px-2 py-0.5 rounded">Auto-included</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="flex-1 bg-gray-50 border border-gray-200 rounded-lg p-3">
                <p className="text-sm text-gray-600 font-mono break-all">
                  {portalLink || `${window.location.origin}/portal/${documentType}/...`}
                </p>
              </div>
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={handleCopyLink}
                className="flex-shrink-0"
              >
                {linkCopied ? (
                  <Check className="h-4 w-4 text-green-600" />
                ) : (
                  <Copy className="h-4 w-4" />
                )}
              </Button>
            </div>
            <p className="text-xs text-muted-foreground">
              This secure link will be automatically added to your {sendMethod === "sms" ? "SMS" : "email"}.
              The recipient can use it to view and {documentType === "estimate" ? "approve" : "pay"} online.
            </p>
          </div>

          {/* Action Buttons */}
          <div className="flex justify-between pt-4 border-t">
            <Button variant="outline" onClick={onClose} disabled={isProcessing}>
              <ArrowLeft className="h-4 w-4 mr-2" />
              Cancel
            </Button>
            
            <Button 
              onClick={handleSend}
              disabled={isProcessing || !sendTo.trim() || !!validationError}
              className="gap-2"
            >
              {isProcessing ? (
                <>
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
                  Sending...
                </>
              ) : (
                <>
                  <Send className="h-4 w-4" />
                  Send {sendMethod === "email" ? "Email" : "SMS"}
                </>
              )}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};
