import { useState, useEffect, useCallback } from 'react';
import { useParams } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import QRCode from 'react-qr-code';
import {
  DocumentHeader,
  DocumentItemsTable,
  DocumentTotals,
  DocumentNotes,
} from '@/components/documents/DocumentComponents';
import { PortalThemeProvider, usePortalTheme } from '@/components/portal/PortalThemeProvider';
import { PortalActionBar } from '@/components/portal/PortalActionBar';
import { PortalLoadingSkeleton } from '@/components/portal/PortalLoadingSkeleton';
import { PortalErrorState } from '@/components/portal/PortalErrorState';
import { PortalRoleBanner } from '@/components/portal/PortalRoleBanner';
import { PortalUpsellSection, type UpsellItem } from '@/components/portal/PortalUpsellSection';
import { cn } from '@/lib/utils';
import { generateFromEmail } from '@/utils/emailUtils';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { XCircle } from 'lucide-react';

interface EstimateData {
  id: string;
  estimate_number: string;
  status: string;
  description?: string;
  notes?: string;
  terms?: string;
  created_at: string;
  valid_until?: string;
  tax_rate?: number;
  tax_amount?: number;
  discount_amount?: number;
  total?: number;
  subtotal?: number;
  job_id?: string;
  client_id?: string;
  contact_role?: 'owner' | 'tenant' | 'property_manager' | 'emergency_contact';
}

interface JobData {
  id: string;
  title: string;
  description?: string;
  property_id?: string;
}

interface ClientData {
  id: string;
  name: string;
  email?: string;
  phone?: string;
  company?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
}

interface PropertyData {
  id: string;
  property_name?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  property_type?: string;
}

interface CompanyData {
  name?: string;
  email?: string;
  phone?: string;
  website?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  logo?: string;
  gstHstNumber?: string;
  autoGeneratedEmail?: string;
  purchasedPhoneNumber?: string;
}

interface LineItem {
  id: string;
  name?: string;
  description?: string;
  quantity?: string | number;
  rate?: string | number;
  price?: string | number;
  amount?: string | number;
  total?: string | number;
}

function EstimatePortalContent() {
  const { token } = useParams<{ token: string }>();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [estimate, setEstimate] = useState<EstimateData | null>(null);
  const [job, setJob] = useState<JobData | null>(null);
  const [client, setClient] = useState<ClientData | null>(null);
  const [property, setProperty] = useState<PropertyData | null>(null);
  const [company, setCompany] = useState<CompanyData | null>(null);
  const [lineItems, setLineItems] = useState<LineItem[]>([]);
  const [upsellItems, setUpsellItems] = useState<UpsellItem[]>([]);
  const [upsellAutoSelect, setUpsellAutoSelect] = useState(true); // Default: auto-select upsells
  const [selectedUpsellTotal, setSelectedUpsellTotal] = useState(0);
  const [selectedUpsellItems, setSelectedUpsellItems] = useState<UpsellItem[]>([]);
  const { toast } = useToast();
  const { isDark } = usePortalTheme();

  const loadEstimateData = useCallback(async () => {
    if (!token) {
      setError('Invalid access link. Please check your URL and try again.');
      setLoading(false);
      return;
    }

    try {
      setLoading(true);
      setError(null);

      // Load estimate by portal access token
      const { data: estimateData, error: estimateError } = await supabase
        .from('estimates')
        .select('*')
        .eq('portal_access_token', token)
        .maybeSingle();

      if (estimateError) {
        console.error('Estimate fetch error:', estimateError);
        throw new Error('Unable to load estimate. Please try again.');
      }

      if (!estimateData) {
        setError('This estimate could not be found or the link has expired.');
        setLoading(false);
        return;
      }

      setEstimate(estimateData);

      // Load related data in parallel for better performance
      const promises: Promise<void>[] = [];

      // Load job if exists
      if (estimateData.job_id) {
        promises.push(
          supabase
            .from('jobs')
            .select('id, title, description, property_id')
            .eq('id', estimateData.job_id)
            .maybeSingle()
            .then(({ data: jobData }) => {
              if (jobData) {
                setJob(jobData);
                // Load property if job has one
                if (jobData.property_id) {
                  return supabase
                    .from('client_properties')
                    .select('id, property_name, address, city, state, zip, property_type')
                    .eq('id', jobData.property_id)
                    .maybeSingle()
                    .then(({ data: propertyData }) => {
                      if (propertyData) setProperty(propertyData);
                    });
                }
              }
            })
        );
      }

      // Load client if exists
      if (estimateData.client_id) {
        promises.push(
          supabase
            .from('clients')
            .select('id, name, email, phone, company, address, city, state, zip')
            .eq('id', estimateData.client_id)
            .maybeSingle()
            .then(({ data: clientData }) => {
              if (clientData) setClient(clientData);
            })
        );
      }

      // Load line items
      promises.push(
        supabase
          .from('line_items')
          .select('*')
          .eq('parent_type', 'estimate')
          .eq('parent_id', estimateData.id)
          .order('created_at', { ascending: true })
          .then(({ data: lineItemsData }) => {
            if (lineItemsData) setLineItems(lineItemsData);
          })
      );

      // Load company settings with purchased phone and auto-generated email
      promises.push(
        (async () => {
          const { data: companyData } = await supabase
            .from('company_settings')
            .select('*')
            .limit(1)
            .maybeSingle();

          if (companyData) {
            // Get organization_id from the company settings user
            let purchasedPhone = '';
            if (companyData.user_id) {
              const { data: profileData } = await supabase
                .from('profiles')
                .select('organization_id')
                .eq('id', companyData.user_id)
                .maybeSingle();

              if (profileData?.organization_id) {
                // Try to get primary purchased phone number
                const { data: phoneData } = await supabase
                  .from('phone_numbers')
                  .select('phone_number')
                  .eq('organization_id', profileData.organization_id)
                  .eq('is_primary', true)
                  .maybeSingle();

                if (phoneData?.phone_number) {
                  purchasedPhone = phoneData.phone_number;
                } else {
                  // Fallback to any active phone
                  const { data: anyPhone } = await supabase
                    .from('phone_numbers')
                    .select('phone_number')
                    .eq('organization_id', profileData.organization_id)
                    .eq('is_active', true)
                    .limit(1)
                    .maybeSingle();

                  if (anyPhone?.phone_number) {
                    purchasedPhone = anyPhone.phone_number;
                  }
                }
              }
            }

            // Generate auto email from company name
            const companyName = companyData.company_name || '';
            const autoEmail = companyName ? generateFromEmail(companyName) : 'support@fixlify.app';

            setCompany({
              name: companyData.company_name,
              email: companyData.company_email,
              phone: purchasedPhone || companyData.company_phone,
              website: companyData.company_website,
              address: companyData.company_address,
              city: companyData.company_city,
              state: companyData.company_state,
              zip: companyData.company_zip,
              logo: companyData.company_logo_url,
              gstHstNumber: companyData.gst_hst_number,
              autoGeneratedEmail: autoEmail,
              purchasedPhoneNumber: purchasedPhone,
            });

            // Load upsell products if enabled
            const upsellConfig = companyData.upsell_config as any;
            if (upsellConfig?.estimates?.enabled && upsellConfig?.estimates?.products?.length > 0) {
              const productIds = upsellConfig.estimates.products;
              // Get auto_select setting (default true for estimates)
              setUpsellAutoSelect(upsellConfig.estimates.auto_select !== false);

              const { data: productsData } = await supabase
                .from('products')
                .select('id, name, description, price')
                .in('id', productIds);

              if (productsData && productsData.length > 0) {
                setUpsellItems(
                  productsData.map((p, idx) => ({
                    id: p.id,
                    name: p.name,
                    description: p.description || undefined,
                    price: p.price || 0,
                    popular: idx === 0, // Mark first item as popular
                  }))
                );
              }
            }
          }
        })()
      );

      await Promise.all(promises);
    } catch (err) {
      console.error('Error loading estimate:', err);
      setError(
        err instanceof Error
          ? err.message
          : 'Failed to load estimate. Please try again.'
      );
      toast.error('Failed to load estimate. Please check your link and try again.');
    } finally {
      setLoading(false);
    }
  }, [token, toast]);

  useEffect(() => {
    loadEstimateData();
  }, [loadEstimateData]);

  // Track view when estimate loads successfully
  useEffect(() => {
    const trackView = async () => {
      if (!estimate || !token) return;

      try {
        const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
        const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

        // Call the portal-view-estimate edge function
        const response = await fetch(`${supabaseUrl}/functions/v1/portal-view-estimate`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'apikey': supabaseAnonKey,
          },
          body: JSON.stringify({
            accessToken: token,
            estimateId: estimate.id,
          }),
        });

        const data = await response.json();
        console.log('[EstimatePortal] View tracking response:', data);
      } catch (err) {
        // Silently fail - view tracking is not critical
        console.warn('[EstimatePortal] Failed to track view:', err);
      }
    };

    trackView();
  }, [estimate?.id, token]);

  const [isAccepting, setIsAccepting] = useState(false);
  const [isDeclining, setIsDeclining] = useState(false);
  const [showDeclineDialog, setShowDeclineDialog] = useState(false);
  const [declineReason, setDeclineReason] = useState('');

  const handleAccept = useCallback(async () => {
    if (!estimate || !token) return;

    setIsAccepting(true);
    try {
      // Get the Supabase URL from the client
      const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
      const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

      // Call the portal-approve-estimate edge function directly
      // This is a public endpoint (no JWT required) that validates via portal_access_token
      const response = await fetch(`${supabaseUrl}/functions/v1/portal-approve-estimate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'apikey': supabaseAnonKey,
        },
        body: JSON.stringify({
          accessToken: token,
          estimateId: estimate.id,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        console.error('Error approving estimate:', data);
        toast.error(data?.error || 'Failed to approve estimate. Please try again or contact support.');
        return;
      }

      if (data?.success) {
        toast.success('Estimate approved successfully! Thank you for your business.');
        // Update local state to reflect the approval
        setEstimate((prev) => prev ? { ...prev, status: 'approved' } : null);
      } else {
        toast.error(data?.error || 'Failed to approve estimate. Please try again.');
      }
    } catch (err) {
      console.error('Error approving estimate:', err);
      toast.error('An unexpected error occurred. Please try again.');
    } finally {
      setIsAccepting(false);
    }
  }, [estimate, token, toast]);

  const handleDecline = useCallback(async () => {
    if (!estimate || !token) return;

    setIsDeclining(true);
    try {
      const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
      const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

      const response = await fetch(`${supabaseUrl}/functions/v1/portal-decline-estimate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'apikey': supabaseAnonKey,
        },
        body: JSON.stringify({
          accessToken: token,
          estimateId: estimate.id,
          reason: declineReason.trim() || undefined,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        console.error('Error declining estimate:', data);
        toast.error(data?.error || 'Failed to decline estimate. Please try again.');
        return;
      }

      if (data?.success) {
        toast.success('Estimate declined. We appreciate your feedback.');
        setEstimate((prev) => prev ? { ...prev, status: 'declined' } : null);
        setShowDeclineDialog(false);
        setDeclineReason('');
      } else {
        toast.error(data?.error || 'Failed to decline estimate. Please try again.');
      }
    } catch (err) {
      console.error('Error declining estimate:', err);
      toast.error('An unexpected error occurred. Please try again.');
    } finally {
      setIsDeclining(false);
    }
  }, [estimate, token, declineReason, toast]);

  // Handle upsell selection changes
  const handleUpsellSelectionChange = useCallback((items: UpsellItem[], totalAmount: number) => {
    setSelectedUpsellItems(items);
    setSelectedUpsellTotal(totalAmount);
  }, []);

  // Loading state
  if (loading) {
    return <PortalLoadingSkeleton documentType="estimate" />;
  }

  // Error state
  if (error || !estimate) {
    return (
      <PortalErrorState
        type={!estimate ? 'not_found' : 'generic'}
        message={error || undefined}
        onRetry={loadEstimateData}
        supportEmail={company?.email}
      />
    );
  }

  // Calculate totals
  const productItems = lineItems.filter(
    (item) =>
      !item.name?.toLowerCase().includes('tax') &&
      !item.description?.toLowerCase().includes('tax')
  );

  const baseSubtotal = productItems.reduce((sum, item) => {
    const amount = parseFloat(String(item.total || item.amount || '0'));
    return sum + amount;
  }, 0);

  // Include selected upsells in subtotal
  const subtotal = baseSubtotal + selectedUpsellTotal;

  const taxRate = estimate.tax_rate || 0;
  // Recalculate tax including upsells
  const taxAmount = (subtotal * taxRate) / 100;
  const discountAmount = estimate.discount_amount || 0;
  // Calculate new total with upsells
  const total = subtotal + taxAmount - discountAmount;

  // Check if estimate can be accepted
  const canAccept =
    estimate.status !== 'accepted' &&
    estimate.status !== 'declined' &&
    estimate.status !== 'expired';

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950 flex flex-col">
      {/* Action Bar */}
      <PortalActionBar
        documentType="estimate"
        documentNumber={estimate.estimate_number}
        status={estimate.status}
        companyName={company?.name}
        onPrimaryAction={canAccept ? handleAccept : undefined}
        primaryActionLabel={isAccepting ? "Approving..." : "Accept Estimate"}
        primaryActionDisabled={isAccepting || isDeclining}
      >
        {/* Decline button */}
        {canAccept && (
          <Button
            variant="outline"
            size="sm"
            onClick={() => setShowDeclineDialog(true)}
            disabled={isAccepting || isDeclining}
            className="hidden sm:flex items-center gap-1.5 border-red-200 text-red-600 hover:bg-red-50 hover:text-red-700 dark:border-red-800 dark:text-red-400 dark:hover:bg-red-900/20"
          >
            <XCircle className="h-4 w-4" />
            <span>Decline</span>
          </Button>
        )}
      </PortalActionBar>

      {/* Decline Reason Dialog */}
      <Dialog open={showDeclineDialog} onOpenChange={setShowDeclineDialog}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Decline Estimate</DialogTitle>
            <DialogDescription>
              We're sorry this estimate doesn't work for you. Would you like to share why?
            </DialogDescription>
          </DialogHeader>
          <div className="py-4">
            <Textarea
              placeholder="Optional: Let us know what we could improve or why this doesn't meet your needs..."
              value={declineReason}
              onChange={(e) => setDeclineReason(e.target.value)}
              rows={4}
              className="resize-none"
            />
          </div>
          <DialogFooter className="flex-col sm:flex-row gap-2">
            <Button
              variant="outline"
              onClick={() => {
                setShowDeclineDialog(false);
                setDeclineReason('');
              }}
              disabled={isDeclining}
            >
              Cancel
            </Button>
            <Button
              variant="destructive"
              onClick={handleDecline}
              disabled={isDeclining}
            >
              {isDeclining ? "Declining..." : "Decline Estimate"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Main Content */}
      <main className="flex-1">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-6 sm:py-8">
          {/* Role Context Banner */}
          {estimate.contact_role && (
            <PortalRoleBanner
              viewerName={client?.name || 'Customer'}
              viewerRole={estimate.contact_role}
              viewerEmail={client?.email}
              documentType="estimate"
              serviceAddress={
                property
                  ? [property.address, property.city, property.state, property.zip]
                      .filter(Boolean)
                      .join(', ')
                  : undefined
              }
              serviceForName={client?.name}
              isBillingContact={true}
              onApprove={canAccept ? handleAccept : undefined}
              onContactSupport={
                company?.email
                  ? () => window.open(`mailto:${company.email}`, '_blank')
                  : undefined
              }
              className="mb-6"
            />
          )}

          <div className="bg-white dark:bg-gray-900 rounded-2xl shadow-lg overflow-hidden">
            {/* Header with Company and Client Info */}
            <DocumentHeader
              type="estimate"
              documentNumber={estimate.estimate_number}
              date={estimate.created_at}
              validUntil={estimate.valid_until}
              status={estimate.status}
              company={company || undefined}
              client={client || undefined}
              property={
                property
                  ? {
                      name: property.property_name,
                      address: property.address,
                      city: property.city,
                      state: property.state,
                      zip: property.zip,
                      type: property.property_type,
                    }
                  : undefined
              }
              contactRole={estimate.contact_role}
            />

            {/* Job Information */}
            {job && (
              <div className="px-6 sm:px-8 py-4 sm:py-6 border-t border-gray-100 dark:border-gray-800">
                <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
                  <div>
                    <h3 className="text-xs sm:text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                      Job Reference
                    </h3>
                    <p className="mt-1 text-base sm:text-lg text-gray-900 dark:text-white">
                      {job.title}
                    </p>
                  </div>
                  {estimate.valid_until && (
                    <div className="text-left sm:text-right">
                      <h3 className="text-xs sm:text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        Valid Until
                      </h3>
                      <p className="mt-1 text-base sm:text-lg text-gray-900 dark:text-white">
                        {new Date(estimate.valid_until).toLocaleDateString('en-US', {
                          year: 'numeric',
                          month: 'long',
                          day: 'numeric',
                        })}
                      </p>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Description */}
            {estimate.description && (
              <div className="px-6 sm:px-8 py-4 sm:py-6 border-t border-gray-100 dark:border-gray-800">
                <h3 className="text-xs sm:text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-2 sm:mb-3">
                  Description
                </h3>
                <p className="text-sm sm:text-base text-gray-700 dark:text-gray-300 whitespace-pre-wrap">
                  {estimate.description}
                </p>
              </div>
            )}

            {/* Line Items */}
            {productItems.length > 0 && (
              <div className="px-6 sm:px-8 py-4 sm:py-6 border-t border-gray-100 dark:border-gray-800">
                <h3 className="text-xs sm:text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-3 sm:mb-4">
                  Items
                </h3>
                <DocumentItemsTable items={productItems} />
              </div>
            )}

            {/* Upsell Recommendations with Checkboxes */}
            {upsellItems.length > 0 && (
              <div className="border-t border-gray-100 dark:border-gray-800">
                <PortalUpsellSection
                  items={upsellItems}
                  companyName={company?.name}
                  documentType="estimate"
                  defaultSelected={upsellAutoSelect}
                  onSelectionChange={handleUpsellSelectionChange}
                  onLearnMore={(item) => {
                    toast.info(`Contact ${company?.name || 'us'} to learn more about ${item.name}`);
                  }}
                />
              </div>
            )}

            {/* Totals and Notes */}
            <div className="px-6 sm:px-8 py-4 sm:py-6 border-t border-gray-100 dark:border-gray-800 bg-gray-50 dark:bg-gray-800/50">
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 sm:gap-8">
                {/* Notes */}
                <div className="order-2 lg:order-1">
                  {estimate.notes && (
                    <DocumentNotes
                      title="Notes"
                      content={estimate.notes}
                      type="info"
                    />
                  )}
                  {estimate.terms && (
                    <DocumentNotes
                      title="Terms & Conditions"
                      content={estimate.terms}
                      type="warning"
                    />
                  )}
                </div>

                {/* Totals */}
                <div className="order-1 lg:order-2">
                  <DocumentTotals
                    subtotal={subtotal}
                    taxAmount={taxAmount}
                    taxRate={taxRate}
                    discountAmount={discountAmount}
                    total={total}
                  />
                </div>
              </div>
            </div>

            {/* Mobile CTA - Sticky at bottom on mobile */}
            {canAccept && (
              <div className="sm:hidden sticky bottom-0 px-4 py-4 bg-white dark:bg-gray-900 border-t border-gray-200 dark:border-gray-800 shadow-lg">
                <div className="flex gap-3">
                  <button
                    onClick={() => setShowDeclineDialog(true)}
                    disabled={isAccepting || isDeclining}
                    className={cn(
                      'flex-shrink-0 py-3 px-4 rounded-lg font-semibold',
                      'border border-red-200 text-red-600 bg-white',
                      'hover:bg-red-50 active:bg-red-100',
                      'dark:border-red-800 dark:text-red-400 dark:bg-gray-900 dark:hover:bg-red-900/20',
                      'transition-colors focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2',
                      'dark:focus:ring-offset-gray-900',
                      'disabled:opacity-50 disabled:cursor-not-allowed'
                    )}
                  >
                    <XCircle className="h-5 w-5" />
                  </button>
                  <button
                    onClick={handleAccept}
                    disabled={isAccepting || isDeclining}
                    className={cn(
                      'flex-1 py-3 px-4 rounded-lg font-semibold text-white',
                      'bg-purple-600 hover:bg-purple-700 active:bg-purple-800',
                      'transition-colors focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-offset-2',
                      'dark:focus:ring-offset-gray-900',
                      'disabled:opacity-50 disabled:cursor-not-allowed'
                    )}
                  >
                    {isAccepting ? "Approving..." : `Accept - $${total.toFixed(2)}`}
                  </button>
                </div>
              </div>
            )}

            {/* Footer */}
            <div
              className={cn(
                'px-6 sm:px-8 py-6 text-white text-center',
                'bg-gradient-to-r from-purple-600 to-purple-700'
              )}
            >
              <p className="text-sm sm:text-base">
                Thank you for considering our services. We look forward to working
                with you!
              </p>
              {company?.email && (
                <p className="text-sm mt-2 opacity-90">
                  Questions? Contact us at{' '}
                  <a
                    href={`mailto:${company.email}`}
                    className="underline hover:no-underline"
                  >
                    {company.email}
                  </a>
                </p>
              )}
            </div>
          </div>

          {/* QR Code Section - Desktop only */}
          <div className="mt-6 hidden sm:flex justify-center print:hidden">
            <div className="bg-white dark:bg-gray-900 rounded-xl shadow-md p-6 text-center">
              <p className="text-sm text-gray-600 dark:text-gray-400 mb-3">
                Scan to view on mobile
              </p>
              <div className="bg-white p-3 inline-block rounded-lg">
                <QRCode
                  value={window.location.href}
                  size={100}
                  level="M"
                  bgColor="#ffffff"
                  fgColor="#000000"
                />
              </div>
            </div>
          </div>

          {/* Powered by footer */}
          <div className="mt-6 text-center print:hidden">
            <p className="text-sm text-gray-400 dark:text-gray-600">
              Powered by{' '}
              <span className="font-medium text-purple-600 dark:text-purple-400">
                Fixlify
              </span>
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}

// Wrapper component with theme provider
export default function EstimatePortal() {
  return (
    <PortalThemeProvider>
      <EstimatePortalContent />
    </PortalThemeProvider>
  );
}
