import { useState, useEffect, useCallback, useMemo } from 'react';
import { useParams } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';
import { DollarSign, CheckCircle, Clock } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { format } from 'date-fns';
import QRCode from 'react-qr-code';
import {
  DocumentHeader,
  DocumentItemsTable,
  DocumentTotals,
  DocumentNotes,
} from '@/components/documents/DocumentComponents';
import { PortalThemeProvider, usePortalTheme } from '@/components/portal/PortalThemeProvider';
import { PortalActionBar } from '@/components/portal/PortalActionBar';
import { PortalLoadingSkeleton } from '@/components/portal/PortalLoadingSkeleton';
import { PortalErrorState } from '@/components/portal/PortalErrorState';
import { PortalRoleBanner } from '@/components/portal/PortalRoleBanner';
import { PortalUpsellSection, type UpsellItem } from '@/components/portal/PortalUpsellSection';
import { cn } from '@/lib/utils';
import { generateFromEmail } from '@/utils/emailUtils';

interface InvoiceData {
  id: string;
  invoice_number: string;
  payment_status: string;
  status?: string;
  description?: string;
  notes?: string;
  terms?: string;
  created_at: string;
  invoice_date?: string;
  due_date?: string;
  tax_rate?: number;
  tax_amount?: number;
  discount_amount?: number;
  total?: number;
  subtotal?: number;
  job_id?: string;
  client_id?: string;
  contact_role?: 'owner' | 'tenant' | 'property_manager' | 'emergency_contact';
}

interface JobData {
  id: string;
  title: string;
  description?: string;
  property_id?: string;
}

interface ClientData {
  id: string;
  name: string;
  email?: string;
  phone?: string;
  company?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
}

interface PropertyData {
  id: string;
  property_name?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  property_type?: string;
}

interface CompanyData {
  name?: string;
  email?: string;
  phone?: string;
  website?: string;
  address?: string;
  city?: string;
  state?: string;
  zip?: string;
  logo?: string;
  gstHstNumber?: string;
  autoGeneratedEmail?: string;
  purchasedPhoneNumber?: string;
}

interface PaymentData {
  id: string;
  amount: number | string;
  method: string;
  status?: string;
  payment_date?: string;
  created_at: string;
  reference?: string;
}

interface LineItem {
  id: string;
  name?: string;
  description?: string;
  quantity?: string | number;
  rate?: string | number;
  price?: string | number;
  amount?: string | number;
  total?: string | number;
}

function InvoicePortalContent() {
  const { token } = useParams<{ token: string }>();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [invoice, setInvoice] = useState<InvoiceData | null>(null);
  const [job, setJob] = useState<JobData | null>(null);
  const [client, setClient] = useState<ClientData | null>(null);
  const [property, setProperty] = useState<PropertyData | null>(null);
  const [company, setCompany] = useState<CompanyData | null>(null);
  const [payments, setPayments] = useState<PaymentData[]>([]);
  const [lineItems, setLineItems] = useState<LineItem[]>([]);
  const [upsellItems, setUpsellItems] = useState<UpsellItem[]>([]);
  const [upsellAutoSelect, setUpsellAutoSelect] = useState(false); // Default: NOT auto-select for invoices
  const [selectedUpsellTotal, setSelectedUpsellTotal] = useState(0);
  const [selectedUpsellItems, setSelectedUpsellItems] = useState<UpsellItem[]>([]);
  const { toast } = useToast();
  const { isDark } = usePortalTheme();

  const loadInvoiceData = useCallback(async () => {
    if (!token) {
      setError('Invalid access link. Please check your URL and try again.');
      setLoading(false);
      return;
    }

    try {
      setLoading(true);
      setError(null);

      // Load invoice by portal access token
      const { data: invoiceData, error: invoiceError } = await supabase
        .from('invoices')
        .select('*')
        .eq('portal_access_token', token)
        .maybeSingle();

      if (invoiceError) {
        console.error('Invoice fetch error:', invoiceError);
        throw new Error('Unable to load invoice. Please try again.');
      }

      if (!invoiceData) {
        setError('This invoice could not be found or the link has expired.');
        setLoading(false);
        return;
      }

      setInvoice(invoiceData);

      // Load related data in parallel for better performance
      const promises: Promise<void>[] = [];

      // Load job if exists
      if (invoiceData.job_id) {
        promises.push(
          supabase
            .from('jobs')
            .select('id, title, description, property_id')
            .eq('id', invoiceData.job_id)
            .maybeSingle()
            .then(({ data: jobData }) => {
              if (jobData) {
                setJob(jobData);
                // Load property if job has one
                if (jobData.property_id) {
                  return supabase
                    .from('client_properties')
                    .select('id, property_name, address, city, state, zip, property_type')
                    .eq('id', jobData.property_id)
                    .maybeSingle()
                    .then(({ data: propertyData }) => {
                      if (propertyData) setProperty(propertyData);
                    });
                }
              }
            })
        );
      }

      // Load client if exists
      if (invoiceData.client_id) {
        promises.push(
          supabase
            .from('clients')
            .select('id, name, email, phone, company, address, city, state, zip')
            .eq('id', invoiceData.client_id)
            .maybeSingle()
            .then(({ data: clientData }) => {
              if (clientData) setClient(clientData);
            })
        );
      }

      // Load payments
      promises.push(
        supabase
          .from('payments')
          .select('*')
          .eq('invoice_id', invoiceData.id)
          .order('payment_date', { ascending: false })
          .then(({ data: paymentsData }) => {
            if (paymentsData) setPayments(paymentsData);
          })
      );

      // Load line items
      promises.push(
        supabase
          .from('line_items')
          .select('*')
          .eq('parent_type', 'invoice')
          .eq('parent_id', invoiceData.id)
          .order('created_at', { ascending: true })
          .then(({ data: lineItemsData }) => {
            if (lineItemsData) setLineItems(lineItemsData);
          })
      );

      // Load company settings with purchased phone and auto-generated email
      promises.push(
        (async () => {
          const { data: companyData } = await supabase
            .from('company_settings')
            .select('*')
            .limit(1)
            .maybeSingle();

          if (companyData) {
            // Get organization_id from the company settings user
            let purchasedPhone = '';
            if (companyData.user_id) {
              const { data: profileData } = await supabase
                .from('profiles')
                .select('organization_id')
                .eq('id', companyData.user_id)
                .maybeSingle();

              if (profileData?.organization_id) {
                // Try to get primary purchased phone number
                const { data: phoneData } = await supabase
                  .from('phone_numbers')
                  .select('phone_number')
                  .eq('organization_id', profileData.organization_id)
                  .eq('is_primary', true)
                  .maybeSingle();

                if (phoneData?.phone_number) {
                  purchasedPhone = phoneData.phone_number;
                } else {
                  // Fallback to any active phone
                  const { data: anyPhone } = await supabase
                    .from('phone_numbers')
                    .select('phone_number')
                    .eq('organization_id', profileData.organization_id)
                    .eq('is_active', true)
                    .limit(1)
                    .maybeSingle();

                  if (anyPhone?.phone_number) {
                    purchasedPhone = anyPhone.phone_number;
                  }
                }
              }
            }

            // Generate auto email from company name
            const companyName = companyData.company_name || '';
            const autoEmail = companyName ? generateFromEmail(companyName) : 'support@fixlify.app';

            setCompany({
              name: companyData.company_name,
              email: companyData.company_email,
              phone: purchasedPhone || companyData.company_phone,
              website: companyData.company_website,
              address: companyData.company_address,
              city: companyData.company_city,
              state: companyData.company_state,
              zip: companyData.company_zip,
              logo: companyData.company_logo_url,
              gstHstNumber: companyData.gst_hst_number,
              autoGeneratedEmail: autoEmail,
              purchasedPhoneNumber: purchasedPhone,
            });

            // Load upsell products if enabled
            const upsellConfig = companyData.upsell_config as any;
            if (upsellConfig?.invoices?.enabled && upsellConfig?.invoices?.products?.length > 0) {
              const productIds = upsellConfig.invoices.products;
              // Get auto_select setting (default false for invoices)
              setUpsellAutoSelect(upsellConfig.invoices.auto_select === true);

              const { data: productsData } = await supabase
                .from('products')
                .select('id, name, description, price')
                .in('id', productIds);

              if (productsData && productsData.length > 0) {
                setUpsellItems(
                  productsData.map((p, idx) => ({
                    id: p.id,
                    name: p.name,
                    description: p.description || undefined,
                    price: p.price || 0,
                    popular: idx === 0, // Mark first item as popular
                  }))
                );
              }
            }
          }
        })()
      );

      await Promise.all(promises);
    } catch (err) {
      console.error('Error loading invoice:', err);
      setError(
        err instanceof Error
          ? err.message
          : 'Failed to load invoice. Please try again.'
      );
      toast.error('Failed to load invoice. Please check your link and try again.');
    } finally {
      setLoading(false);
    }
  }, [token, toast]);

  useEffect(() => {
    loadInvoiceData();
  }, [loadInvoiceData]);

  // Track view when invoice loads successfully
  useEffect(() => {
    const trackView = async () => {
      if (!invoice || !token) return;

      try {
        const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
        const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

        // Call the portal-view-invoice edge function
        const response = await fetch(`${supabaseUrl}/functions/v1/portal-view-invoice`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'apikey': supabaseAnonKey,
          },
          body: JSON.stringify({
            accessToken: token,
            invoiceId: invoice.id,
          }),
        });

        const data = await response.json();
        console.log('[InvoicePortal] View tracking response:', data);
      } catch (err) {
        // Silently fail - view tracking is not critical
        console.warn('[InvoicePortal] Failed to track view:', err);
      }
    };

    trackView();
  }, [invoice?.id, token]);

  const handlePayNow = useCallback(() => {
    toast.info(
      'Online payment will be available soon. Please contact us for payment options.'
    );
    // TODO: Implement online payment flow (Stripe integration)
  }, [toast]);

  // Handle upsell selection changes
  const handleUpsellSelectionChange = useCallback((items: UpsellItem[], totalAmount: number) => {
    setSelectedUpsellItems(items);
    setSelectedUpsellTotal(totalAmount);
  }, []);

  // Utility functions
  const formatCurrency = useCallback((amount: number) => {
    return `$${Math.abs(amount).toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',')}`;
  }, []);

  const formatPaymentMethod = useCallback((method: string) => {
    return method
      .split('-')
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  }, []);

  // Map invoice payment status to banner status
  const mapPaymentStatus = useCallback(
    (status: string): 'unpaid' | 'partial' | 'paid' | 'overdue' => {
      if (status === 'paid') return 'paid';
      if (status === 'partial') return 'partial';
      if (status === 'overdue') return 'overdue';
      return 'unpaid';
    },
    []
  );

  // Calculate totals
  const calculatedTotals = useMemo(() => {
    if (!invoice) return { subtotal: 0, taxAmount: 0, taxRate: 0, discountAmount: 0, total: 0, totalPaid: 0, balance: 0, isPaid: false };

    const productItems = lineItems.filter(
      (item) =>
        !item.name?.toLowerCase().includes('tax') &&
        !item.description?.toLowerCase().includes('tax')
    );

    const subtotal = productItems.reduce((sum, item) => {
      const amount = parseFloat(String(item.total || item.amount || '0'));
      return sum + amount;
    }, 0);

    const taxRate = invoice.tax_rate || 0;
    const taxAmount = invoice.tax_amount || (subtotal * taxRate) / 100;
    const discountAmount = invoice.discount_amount || 0;
    const total = invoice.total || subtotal + taxAmount - discountAmount;
    const totalPaid = payments.reduce(
      (sum, payment) => sum + (parseFloat(String(payment.amount)) || 0),
      0
    );
    const balance = total - totalPaid;
    const isPaid = invoice.payment_status === 'paid' || balance <= 0;

    return { subtotal, taxAmount, taxRate, discountAmount, total, totalPaid, balance, isPaid, productItems };
  }, [invoice, lineItems, payments]);

  // Loading state
  if (loading) {
    return <PortalLoadingSkeleton documentType="invoice" />;
  }

  // Error state
  if (error || !invoice) {
    return (
      <PortalErrorState
        type={!invoice ? 'not_found' : 'generic'}
        message={error || undefined}
        onRetry={loadInvoiceData}
        supportEmail={company?.email}
      />
    );
  }

  const { subtotal, taxAmount, taxRate, discountAmount, total, totalPaid, balance, isPaid, productItems } = calculatedTotals;

  // Check if payment is needed
  const needsPayment = !isPaid && balance > 0;

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-950 flex flex-col">
      {/* Action Bar */}
      <PortalActionBar
        documentType="invoice"
        documentNumber={invoice.invoice_number}
        status={invoice.payment_status}
        companyName={company?.name}
        balance={balance}
        onPrimaryAction={needsPayment ? handlePayNow : undefined}
        primaryActionLabel={needsPayment ? `Pay ${formatCurrency(balance)}` : undefined}
      />

      {/* Main Content */}
      <main className="flex-1">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-6 sm:py-8">
          {/* Payment Status Banner */}
          {isPaid && (
            <div className="mb-6 bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-xl p-4 flex items-center gap-3">
              <div className="flex-shrink-0 w-10 h-10 bg-green-100 dark:bg-green-900/50 rounded-full flex items-center justify-center">
                <CheckCircle className="h-5 w-5 text-green-600 dark:text-green-400" />
              </div>
              <div>
                <p className="font-semibold text-green-800 dark:text-green-200">
                  Payment Complete
                </p>
                <p className="text-sm text-green-600 dark:text-green-400">
                  Thank you for your payment of {formatCurrency(totalPaid)}
                </p>
              </div>
            </div>
          )}

          {/* Overdue Warning */}
          {invoice.payment_status === 'overdue' && (
            <div className="mb-6 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-xl p-4 flex items-center gap-3">
              <div className="flex-shrink-0 w-10 h-10 bg-red-100 dark:bg-red-900/50 rounded-full flex items-center justify-center">
                <Clock className="h-5 w-5 text-red-600 dark:text-red-400" />
              </div>
              <div>
                <p className="font-semibold text-red-800 dark:text-red-200">
                  Payment Overdue
                </p>
                <p className="text-sm text-red-600 dark:text-red-400">
                  This invoice is past due. Please make payment as soon as possible.
                </p>
              </div>
            </div>
          )}

          {/* Role Context Banner */}
          {invoice.contact_role && (
            <PortalRoleBanner
              viewerName={client?.name || 'Customer'}
              viewerRole={invoice.contact_role}
              viewerEmail={client?.email}
              documentType="invoice"
              serviceAddress={
                property
                  ? [property.address, property.city, property.state, property.zip]
                      .filter(Boolean)
                      .join(', ')
                  : undefined
              }
              serviceForName={client?.name}
              isBillingContact={true}
              paymentStatus={mapPaymentStatus(invoice.payment_status)}
              amountDue={balance > 0 ? balance : undefined}
              onPay={needsPayment ? handlePayNow : undefined}
              onContactSupport={
                company?.email
                  ? () => window.open(`mailto:${company.email}`, '_blank')
                  : undefined
              }
              className="mb-6"
            />
          )}

          <div className="bg-white dark:bg-gray-900 rounded-2xl shadow-lg overflow-hidden">
            {/* Header with Company and Client Info */}
            <DocumentHeader
              type="invoice"
              documentNumber={invoice.invoice_number}
              date={invoice.invoice_date || invoice.created_at}
              dueDate={invoice.due_date}
              status={invoice.payment_status}
              company={company || undefined}
              client={client || undefined}
              property={
                property
                  ? {
                      name: property.property_name,
                      address: property.address,
                      city: property.city,
                      state: property.state,
                      zip: property.zip,
                      type: property.property_type,
                    }
                  : undefined
              }
              contactRole={invoice.contact_role}
            />

            {/* Job Information */}
            {job && (
              <div className="px-6 sm:px-8 py-4 sm:py-6 border-t border-gray-100 dark:border-gray-800">
                <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
                  <div>
                    <h3 className="text-xs sm:text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                      Job Reference
                    </h3>
                    <p className="mt-1 text-base sm:text-lg text-gray-900 dark:text-white">
                      {job.title}
                    </p>
                  </div>
                  {invoice.due_date && (
                    <div className="text-left sm:text-right">
                      <h3 className="text-xs sm:text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                        Due Date
                      </h3>
                      <p className={cn(
                        'mt-1 text-base sm:text-lg font-medium',
                        invoice.payment_status === 'overdue'
                          ? 'text-red-600 dark:text-red-400'
                          : 'text-gray-900 dark:text-white'
                      )}>
                        {format(new Date(invoice.due_date), 'MMMM dd, yyyy')}
                      </p>
                    </div>
                  )}
                </div>
              </div>
            )}

            {/* Description */}
            {invoice.description && (
              <div className="px-6 sm:px-8 py-4 sm:py-6 border-t border-gray-100 dark:border-gray-800">
                <h3 className="text-xs sm:text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-2 sm:mb-3">
                  Description
                </h3>
                <p className="text-sm sm:text-base text-gray-700 dark:text-gray-300 whitespace-pre-wrap">
                  {invoice.description}
                </p>
              </div>
            )}

            {/* Line Items */}
            {productItems && productItems.length > 0 && (
              <div className="px-6 sm:px-8 py-4 sm:py-6 border-t border-gray-100 dark:border-gray-800">
                <h3 className="text-xs sm:text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-3 sm:mb-4">
                  Items
                </h3>
                <DocumentItemsTable items={productItems} />
              </div>
            )}

            {/* Upsell Recommendations with Checkboxes */}
            {upsellItems.length > 0 && (
              <div className="border-t border-gray-100 dark:border-gray-800">
                <PortalUpsellSection
                  items={upsellItems}
                  companyName={company?.name}
                  documentType="invoice"
                  defaultSelected={upsellAutoSelect}
                  onSelectionChange={handleUpsellSelectionChange}
                  onLearnMore={(item) => {
                    toast.info(`Contact ${company?.name || 'us'} to learn more about ${item.name}`);
                  }}
                />
              </div>
            )}

            {/* Payment History */}
            {payments.length > 0 && (
              <div className="px-6 sm:px-8 py-4 sm:py-6 border-t border-gray-100 dark:border-gray-800 bg-gray-50 dark:bg-gray-800/30">
                <h3 className="text-xs sm:text-sm font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-wider mb-3 sm:mb-4">
                  Payment History
                </h3>
                <div className="space-y-3">
                  {payments.map((payment) => (
                    <Card
                      key={payment.id}
                      className="p-3 sm:p-4 bg-white dark:bg-gray-900 border-gray-100 dark:border-gray-800"
                    >
                      <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-2">
                        <div className="flex items-center gap-3 sm:gap-4">
                          <div className="w-9 h-9 sm:w-10 sm:h-10 bg-green-100 dark:bg-green-900/30 rounded-full flex items-center justify-center flex-shrink-0">
                            <DollarSign className="h-4 w-4 sm:h-5 sm:w-5 text-green-600 dark:text-green-400" />
                          </div>
                          <div>
                            <p className="font-semibold text-gray-900 dark:text-white text-sm sm:text-base">
                              {formatCurrency(parseFloat(String(payment.amount)))}
                            </p>
                            <p className="text-xs sm:text-sm text-gray-600 dark:text-gray-400">
                              {formatPaymentMethod(payment.method)} -{' '}
                              {format(
                                new Date(payment.payment_date || payment.created_at),
                                'MMM dd, yyyy'
                              )}
                            </p>
                          </div>
                        </div>
                        <Badge
                          className={cn(
                            'self-start sm:self-center text-xs',
                            payment.status === 'completed'
                              ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300'
                              : 'bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300'
                          )}
                        >
                          {payment.status === 'completed' && (
                            <CheckCircle className="h-3 w-3 mr-1" />
                          )}
                          {payment.status || 'Completed'}
                        </Badge>
                      </div>
                      {payment.reference && (
                        <p className="text-xs text-gray-500 dark:text-gray-500 mt-2 pl-12 sm:pl-14">
                          Ref: {payment.reference}
                        </p>
                      )}
                    </Card>
                  ))}
                </div>
              </div>
            )}

            {/* Totals and Notes */}
            <div className="px-6 sm:px-8 py-4 sm:py-6 border-t border-gray-100 dark:border-gray-800 bg-gray-50 dark:bg-gray-800/50">
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 sm:gap-8">
                {/* Notes */}
                <div className="order-2 lg:order-1">
                  {invoice.notes && (
                    <DocumentNotes
                      title="Notes"
                      content={invoice.notes}
                      type="info"
                    />
                  )}
                  {invoice.terms && (
                    <DocumentNotes
                      title="Terms & Conditions"
                      content={invoice.terms}
                      type="warning"
                    />
                  )}
                </div>

                {/* Totals */}
                <div className="order-1 lg:order-2">
                  <DocumentTotals
                    subtotal={subtotal}
                    taxAmount={taxAmount}
                    taxRate={taxRate}
                    discountAmount={discountAmount}
                    total={total}
                    paidAmount={totalPaid}
                  />
                </div>
              </div>
            </div>

            {/* Mobile CTA - Sticky at bottom on mobile */}
            {needsPayment && (
              <div className="sm:hidden sticky bottom-0 px-4 py-4 bg-white dark:bg-gray-900 border-t border-gray-200 dark:border-gray-800 shadow-lg">
                <button
                  onClick={handlePayNow}
                  className={cn(
                    'w-full py-3 px-4 rounded-lg font-semibold text-white',
                    'bg-green-600 hover:bg-green-700 active:bg-green-800',
                    'transition-colors focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2',
                    'dark:focus:ring-offset-gray-900'
                  )}
                >
                  Pay Now - {formatCurrency(balance)}
                </button>
              </div>
            )}

            {/* Footer */}
            <div
              className={cn(
                'px-6 sm:px-8 py-6 text-white text-center',
                'bg-gradient-to-r from-green-600 to-green-700'
              )}
            >
              <p className="text-sm sm:text-base">
                {isPaid
                  ? 'Thank you for your payment. We appreciate your business!'
                  : 'Thank you for your business. Please remit payment at your earliest convenience.'}
              </p>
              {company?.email && (
                <p className="text-sm mt-2 opacity-90">
                  Questions? Contact us at{' '}
                  <a
                    href={`mailto:${company.email}`}
                    className="underline hover:no-underline"
                  >
                    {company.email}
                  </a>
                </p>
              )}
            </div>
          </div>

          {/* QR Code Section - Desktop only */}
          <div className="mt-6 hidden sm:flex justify-center print:hidden">
            <div className="bg-white dark:bg-gray-900 rounded-xl shadow-md p-6 text-center">
              <p className="text-sm text-gray-600 dark:text-gray-400 mb-3">
                Scan to view on mobile
              </p>
              <div className="bg-white p-3 inline-block rounded-lg">
                <QRCode
                  value={window.location.href}
                  size={100}
                  level="M"
                  bgColor="#ffffff"
                  fgColor="#000000"
                />
              </div>
            </div>
          </div>

          {/* Powered by footer */}
          <div className="mt-6 text-center print:hidden">
            <p className="text-sm text-gray-400 dark:text-gray-600">
              Powered by{' '}
              <span className="font-medium text-green-600 dark:text-green-400">
                Fixlify
              </span>
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}

// Wrapper component with theme provider
export default function InvoicePortal() {
  return (
    <PortalThemeProvider>
      <InvoicePortalContent />
    </PortalThemeProvider>
  );
}
