import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import { Info, Globe, Clock, Loader2, Check, FileText, Shield, Receipt, AlertCircle } from "lucide-react";
import { useState, useEffect, useRef } from "react";
import { formatCompanyNameForEmail, generateFromEmail } from "@/utils/emailUtils";
import { TIMEZONES, DEFAULT_TIMEZONE, getTimezonesGrouped, getCurrentTimeInTimezone } from "@/utils/timezones";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";

// Debounce hook for autosave
function useDebounce<T>(value: T, delay: number): T {
  const [debouncedValue, setDebouncedValue] = useState<T>(value);
  useEffect(() => {
    const handler = setTimeout(() => setDebouncedValue(value), delay);
    return () => clearTimeout(handler);
  }, [value, delay]);
  return debouncedValue;
}

interface CompanyInfoSectionProps {
  companySettings: any;
  updateCompanySettings: (updates: any) => void;
  isEditing?: boolean;
}

export const CompanyInfoSection = ({ companySettings, updateCompanySettings, isEditing = true }: CompanyInfoSectionProps) => {
  const [localSettings, setLocalSettings] = useState(companySettings);
  const [savingField, setSavingField] = useState<string | null>(null);
  const [savedField, setSavedField] = useState<string | null>(null);
  const isInitialMount = useRef(true);

  // Debounced settings for autosave (800ms delay for company info)
  const debouncedSettings = useDebounce(localSettings, 800);

  // Update local settings when companySettings changes
  useEffect(() => {
    setLocalSettings(companySettings);
    isInitialMount.current = true; // Reset on external update
  }, [companySettings]);

  // Autosave effect - triggers when debounced settings changes
  useEffect(() => {
    // Skip initial mount to prevent saving on load
    if (isInitialMount.current) {
      isInitialMount.current = false;
      return;
    }

    // Check if there are actual changes
    const hasChanges = JSON.stringify(debouncedSettings) !== JSON.stringify(companySettings);
    if (!hasChanges) return;

    saveSettings();
  }, [debouncedSettings]);

  const saveSettings = async () => {
    setSavingField('company');
    try {
      await updateCompanySettings(debouncedSettings);
      setSavingField(null);
      setSavedField('company');
      setTimeout(() => setSavedField(null), 2000);
    } catch (error) {
      console.error('CompanyInfoSection - Error saving company settings:', error);
      setSavingField(null);
      toast.error('Failed to save company information');
    }
  };

  const handleFieldChange = (field: string, value: string) => {
    setLocalSettings(prev => ({ ...prev, [field]: value }));
  };

  // Save indicator component
  const SaveIndicator = () => {
    if (savingField === 'company') {
      return <Loader2 className="h-4 w-4 animate-spin text-muted-foreground" />;
    }
    if (savedField === 'company') {
      return <Check className="h-4 w-4 text-emerald-500" />;
    }
    return null;
  };

  // Document usage badge - shows that a field is used in invoices/estimates
  const DocumentUsageBadge = ({ tooltip }: { tooltip: string }) => (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <Badge variant="outline" className="ml-2 bg-blue-50 text-blue-700 border-blue-200 text-[10px] px-1.5 py-0 h-5 gap-1">
            <FileText className="h-3 w-3" />
            Used in Documents
          </Badge>
        </TooltipTrigger>
        <TooltipContent>
          <p className="text-xs max-w-xs">{tooltip}</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );

  // Get the auto-generated email address
  const getAutoGeneratedEmail = () => {
    const companyName = localSettings.company_name || '';
    if (!companyName.trim()) {
      return 'support@fixlify.app';
    }
    return generateFromEmail(companyName);
  };

  const getFormattedName = () => {
    const companyName = localSettings.company_name || '';
    if (!companyName.trim()) {
      return 'support';
    }
    return formatCompanyNameForEmail(companyName);
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-medium">Company Information</h3>
        <SaveIndicator />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="space-y-2">
          <div className="flex items-center">
            <Label htmlFor="company-name">Company Name *</Label>
            <DocumentUsageBadge tooltip="Displayed in the header of your estimates and invoices" />
          </div>
          <Input
            id="company-name"
            value={localSettings.company_name || ''}
            onChange={(e) => handleFieldChange('company_name', e.target.value)}
            disabled={!isEditing}
            placeholder="Enter your company name"
            className=""
            required
          />
          <p className="text-xs text-muted-foreground">
            This will be used to generate your email address automatically
          </p>
        </div>

        {/* Auto-Generated Email Section */}
        <div className="space-y-2 md:col-span-2">
          <Label>Auto-Generated Email Address</Label>
          <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
            <div className="flex items-start gap-3">
              <Info className="h-5 w-5 text-blue-600 mt-0.5" />
              <div className="flex-1">
                <h4 className="font-medium text-blue-800">Automatic Email Generation</h4>
                <div className="mt-2 space-y-2">
                  <p className="text-sm text-blue-700">
                    Based on your company name, your email will be:
                  </p>
                  <div className="flex items-center gap-2">
                    <span className="text-sm text-blue-700">Email address:</span>
                    <Badge variant="secondary" className="bg-green-50 text-green-700">
                      {getAutoGeneratedEmail()}
                    </Badge>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="space-y-2 md:col-span-2">
          <div className="flex items-center">
            <Label htmlFor="company-address">Address</Label>
            <DocumentUsageBadge tooltip="Displayed in the header of your estimates and invoices" />
          </div>
          <Input
            id="company-address"
            value={localSettings.company_address || ''}
            onChange={(e) => handleFieldChange('company_address', e.target.value)}
            disabled={!isEditing}
            placeholder="123 Business Park, Suite 456"
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="company-city">City</Label>
          <Input 
            id="company-city" 
            value={localSettings.company_city || ''}
            onChange={(e) => handleFieldChange('company_city', e.target.value)}
            disabled={!isEditing}
            placeholder="San Francisco"
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="company-state">State</Label>
          <Input 
            id="company-state" 
            value={localSettings.company_state || ''}
            onChange={(e) => handleFieldChange('company_state', e.target.value)}
            disabled={!isEditing}
            placeholder="California"
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="company-zip">ZIP Code</Label>
          <Input 
            id="company-zip" 
            value={localSettings.company_zip || ''}
            onChange={(e) => handleFieldChange('company_zip', e.target.value)}
            disabled={!isEditing}
            placeholder="94103"
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="company-country">Country</Label>
          <Input 
            id="company-country" 
            value={localSettings.company_country || ''}
            onChange={(e) => handleFieldChange('company_country', e.target.value)}
            disabled={!isEditing}
            placeholder="United States"
          />
        </div>
        <div className="space-y-2">
          <div className="flex items-center">
            <Label htmlFor="company-website">Website</Label>
            <DocumentUsageBadge tooltip="Can be displayed in the footer of your estimates and invoices" />
          </div>
          <Input
            id="company-website"
            value={localSettings.company_website || ''}
            onChange={(e) => handleFieldChange('company_website', e.target.value)}
            disabled={!isEditing}
            placeholder="https://www.yourcompany.com"
          />
        </div>
        <div className="space-y-2">
          <Label htmlFor="company-email">Main Business Email</Label>
          <Input 
            id="company-email" 
            type="email"
            value={localSettings.company_email || ''}
            onChange={(e) => handleFieldChange('company_email', e.target.value)}
            disabled={!isEditing}
            placeholder="contact@yourcompany.com"
          />
        </div>
        {/* Legal & Tax Section */}
        <div className="md:col-span-2 pt-4 border-t mt-4">
          <div className="flex items-center gap-2 mb-4">
            <Receipt className="h-4 w-4 text-muted-foreground" />
            <h4 className="font-medium text-sm">Legal & Tax Information</h4>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <div className="flex items-center">
                <Label htmlFor="gst-hst-number">GST/HST Number</Label>
                <DocumentUsageBadge tooltip="Displayed on invoices for Canadian tax compliance (if provided)" />
              </div>
              <Input
                id="gst-hst-number"
                value={localSettings.gst_hst_number || ''}
                onChange={(e) => handleFieldChange('gst_hst_number', e.target.value)}
                disabled={!isEditing}
                placeholder="123456789 RT0001"
              />
              <p className="text-xs text-muted-foreground flex items-center gap-1">
                <AlertCircle className="h-3 w-3" />
                Required if annual revenue exceeds $30,000 CAD
              </p>
            </div>
            <div className="space-y-2">
              <Label htmlFor="tax-id">Tax ID / EIN (US)</Label>
              <Input
                id="tax-id"
                value={localSettings.tax_id || ''}
                onChange={(e) => handleFieldChange('tax_id', e.target.value)}
                disabled={!isEditing}
                placeholder="XX-XXXXXXX"
              />
            </div>
            <div className="space-y-2">
              <div className="flex items-center">
                <Label htmlFor="insurance-policy">
                  <div className="flex items-center gap-1">
                    <Shield className="h-3 w-3" />
                    Insurance Policy Number
                  </div>
                </Label>
              </div>
              <Input
                id="insurance-policy"
                value={localSettings.insurance_policy_number || ''}
                onChange={(e) => handleFieldChange('insurance_policy_number', e.target.value)}
                disabled={!isEditing}
                placeholder="POL-123456789"
              />
              <p className="text-xs text-muted-foreground">
                Optional - can be shown on documents to demonstrate insurance coverage
              </p>
            </div>
          </div>
        </div>
        <div className="space-y-2">
          <Label htmlFor="company-phone">Owner Phone Number</Label>
          <Input 
            id="company-phone" 
            value={localSettings.company_phone || ''}
            onChange={(e) => handleFieldChange('company_phone', e.target.value)}
            disabled={!isEditing}
            placeholder="(555) 123-4567"
          />
          <p className="text-xs text-muted-foreground">
            Your personal contact number. Business phone numbers are managed in Phone Numbers section.
          </p>
        </div>
        
        {/* Timezone Selection */}
        <div className="space-y-2 md:col-span-2">
          <Label htmlFor="company-timezone">
            <div className="flex items-center gap-2">
              <Globe className="h-4 w-4" />
              Business Timezone
            </div>
          </Label>
          <Select
            value={localSettings.company_timezone || DEFAULT_TIMEZONE}
            onValueChange={(value) => handleFieldChange('company_timezone', value)}
            disabled={!isEditing}
          >
            <SelectTrigger>
              <SelectValue placeholder="Select timezone" />
            </SelectTrigger>
            <SelectContent>
              {Object.entries(getTimezonesGrouped()).map(([group, timezones]) => (
                <div key={group}>
                  <div className="px-2 py-1.5 text-sm font-semibold text-muted-foreground">
                    {group}
                  </div>
                  {timezones.map((tz) => (
                    <SelectItem key={tz.value} value={tz.value}>
                      <div className="flex items-center justify-between w-full">
                        <span>{tz.label}</span>
                        <span className="text-xs text-muted-foreground ml-2">
                          UTC{tz.offset}
                        </span>
                      </div>
                    </SelectItem>
                  ))}
                </div>
              ))}
            </SelectContent>
          </Select>
          {localSettings.company_timezone && (
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Clock className="h-3 w-3" />
              Current time: {getCurrentTimeInTimezone(localSettings.company_timezone || DEFAULT_TIMEZONE)}
            </div>
          )}
          <p className="text-xs text-muted-foreground">
            This timezone will be used as the default for all business operations and automation scheduling
          </p>
        </div>
      </div>
    </div>
  );
};
