// This file is automatically generated. Do not edit it directly.
import { createClient, RealtimeChannel, RealtimeChannelOptions } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqppvcrlvsgrsqelglod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xcHB2Y3JsdnNncnNxZWxnbG9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1OTE3MDUsImV4cCI6MjA2MzE2NzcwNX0.My-KiqG1bCMqzUru4m59d4v18N3WGxNoNtFPOFAmhzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    },
    timeout: 20000,
    heartbeatIntervalMs: 30000
  }
});

// Override the channel method to prevent sms_messages subscriptions
const originalChannel = supabaseClient.channel.bind(supabaseClient);
supabaseClient.channel = function(name: string, opts?: RealtimeChannelOptions): RealtimeChannel {
  // Only block specific SMS message channels that cause issues
  if (name === 'sms_messages' || name.includes('sms_messages:')) {
    console.log('Blocked problematic SMS channel:', name);
    // Return a mock channel that does nothing
    const mockChannel = {
      on: () => mockChannel,
      subscribe: () => ({ status: 'SUBSCRIBED' }),
      unsubscribe: () => {},
      presenceState: () => ({}),
      track: () => {},
      untrack: () => {}
    } as RealtimeChannel;
    return mockChannel;
  }
  return originalChannel(name, opts);
};

// Override removeChannel to prevent errors
const originalRemoveChannel = supabaseClient.removeChannel.bind(supabaseClient);
supabaseClient.removeChannel = function(channel: RealtimeChannel): Promise<void> {
  try {
    // Check if channel is valid
    if (!channel) {
      console.log('No channel to remove');
      return Promise.resolve();
    }
    
    // Check if this is our mock channel
    if (channel && typeof channel.unsubscribe === 'function' && channel.unsubscribe.toString().includes('{}')) {
      // This is our mock channel, just return resolved promise
      return Promise.resolve();
    }
    
    // For real channels, use the original method
    if (channel && typeof channel.unsubscribe === 'function') {
      return originalRemoveChannel(channel);
    }
    
    return Promise.resolve();
  } catch (error) {
    console.log('Suppressed removeChannel error:', error);
    return Promise.resolve();
  }
};

export const supabase = supabaseClient;