import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { formatCompanyNameForEmail, generateFromEmail } from "@/utils/emailUtils";

interface CompanyInfo {
  name: string;
  businessType: string;
  address: string;
  city: string;
  state: string;
  zip: string;
  country: string;
  phone: string;
  email: string;
  website: string;
  taxId: string;
  logoUrl: string;
  tagline: string;
  description: string;
  emailDomainName: string;
  emailFromName: string;
  emailFromAddress: string;
  // New fields for Canadian legal compliance
  gstHstNumber: string;
  insurancePolicyNumber: string;
  // Auto-generated fields
  autoGeneratedEmail: string;
  purchasedPhoneNumber: string;
}

export const useCompanySettings = () => {
  const [companyInfo, setCompanyInfo] = useState<CompanyInfo | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
  const fetchCompanySettings = async () => {
    try {
      console.log('=== useCompanySettings - Starting fetch ===');
      const { data: { user } } = await supabase.auth.getUser();
      console.log('Current user:', user?.id);
      if (!user) {
        console.log('No user found, setting loading to false');
        setLoading(false);
        return;
      }

      // Get user's organization_id from profile
      const { data: profileData, error: profileError } = await supabase
        .from('profiles')
        .select('organization_id, company_name, company_email, company_phone, company_address')
        .eq('id', user.id)
        .single();

      console.log('Querying company_settings for user:', user.id);
      const { data: companySettings, error } = await supabase
        .from('company_settings')
        .select('*')
        .eq('user_id', user.id)
        .maybeSingle();

      // Fetch purchased phone number for the organization
      let purchasedPhone = '';
      if (profileData?.organization_id) {
        const { data: phoneData } = await supabase
          .from('phone_numbers')
          .select('phone_number, friendly_name')
          .eq('organization_id', profileData.organization_id)
          .eq('is_primary', true)
          .maybeSingle();

        if (phoneData?.phone_number) {
          purchasedPhone = phoneData.phone_number;
        } else {
          // Try to get any active phone number for the org
          const { data: anyPhone } = await supabase
            .from('phone_numbers')
            .select('phone_number')
            .eq('organization_id', profileData.organization_id)
            .eq('is_active', true)
            .limit(1)
            .maybeSingle();

          if (anyPhone?.phone_number) {
            purchasedPhone = anyPhone.phone_number;
          }
        }
      }

      console.log('Company settings query result:', { companySettings, error });
      console.log('Profile data query result:', { profileData, profileError });
      console.log('Purchased phone number:', purchasedPhone);

      if (companySettings) {
        console.log('Found company settings, setting company info');
        const companyName = profileData?.company_name || companySettings.company_name || '';
        const autoEmail = companyName ? generateFromEmail(companyName) : 'support@fixlify.app';

        setCompanyInfo({
            // Use profile company name if available, otherwise fall back to company_settings
            name: companyName,
            businessType: companySettings.business_type || '',
            address: companySettings.company_address || '',
            city: companySettings.company_city || '',
            state: companySettings.company_state || '',
            zip: companySettings.company_zip || '',
            country: companySettings.company_country || '',
            // Use purchased phone number if available, otherwise owner phone
            phone: purchasedPhone || companySettings.company_phone || '',
            email: companySettings.company_email || '',
            website: companySettings.company_website || '',
            taxId: companySettings.tax_id || '',
            logoUrl: companySettings.company_logo_url || '',
            tagline: companySettings.company_tagline || '',
            description: companySettings.company_description || '',
            emailDomainName: companySettings.custom_domain_name || '',
            emailFromName: companySettings.email_from_name || '',
            emailFromAddress: companySettings.email_from_address || '',
            // New fields
            gstHstNumber: companySettings.gst_hst_number || '',
            insurancePolicyNumber: companySettings.insurance_policy_number || '',
            autoGeneratedEmail: autoEmail,
            purchasedPhoneNumber: purchasedPhone
          });
        } else {
          // Fallback company info with all required properties
          setCompanyInfo({
            name: 'Fixlify Services',
            businessType: 'Professional Service Solutions',
            address: '456 Professional Ave, Suite 100',
            city: 'Business City',
            state: 'BC',
            zip: 'V1V 1V1',
            country: 'United States',
            phone: purchasedPhone || '(555) 123-4567',
            email: 'info@fixlify.com',
            website: 'www.fixlify.com',
            taxId: '',
            logoUrl: '',
            tagline: 'Professional Service You Can Trust',
            description: 'Licensed & Insured Professional Services',
            emailDomainName: '',
            emailFromName: 'Support Team',
            emailFromAddress: '',
            gstHstNumber: '',
            insurancePolicyNumber: '',
            autoGeneratedEmail: 'support@fixlify.app',
            purchasedPhoneNumber: purchasedPhone
          });
        }
      } catch (error) {
        console.error('Error fetching company settings:', error);
        // Set fallback data on error with all required properties
        setCompanyInfo({
          name: 'Fixlify Services',
          businessType: 'Professional Service Solutions',
          phone: '(555) 123-4567',
          email: 'info@fixlyfy.com',
          address: '456 Professional Ave, Suite 100',
          city: 'Business City',
          state: 'BC',
          zip: 'V1V 1V1',
          country: 'Canada',
          website: 'www.fixlyfy.com',
          taxId: '',
          logoUrl: '',
          tagline: 'Professional Service You Can Trust',
          description: 'Licensed & Insured Professional Services',
          emailDomainName: '',
          emailFromName: 'Support Team',
          emailFromAddress: '',
          gstHstNumber: '',
          insurancePolicyNumber: '',
          autoGeneratedEmail: 'support@fixlify.app',
          purchasedPhoneNumber: ''
        });
      } finally {
        setLoading(false);
      }
    };

    fetchCompanySettings();
  }, []);

  return { companyInfo, loading };
};
